SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_CLASS;
SELECT * FROM TB_STUDENT;
SELECT * FROM TB_PROFESSOR;

--B1번
SELECT DEPARTMENT_NAME AS 학과명, CATEGORY AS 계열
FROM TB_DEPARTMENT;

--B2번
SELECT DEPARTMENT_NAME AS 학과명, CAPACITY AS 정원
FROM  TB_DEPARTMENT;

SELECT DEPARTMENT_NAME ||'의 정원은 ' || CAPACITY || '명입니다' AS 학과별정원
FROM  TB_DEPARTMENT;

--B3번
SELECT STUDENT_NAME AS 학생명
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE ABSENCE_YN = 'N' 
    AND DEPARTMENT_NAME = '국어국문학과'
    AND SUBSTR(STUDENT_SSN, 8,1) IN ('2','4');
    
--B4번
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO IN ('A513079','A513090','A513091','A513110','A513119');

--B5번
SELECT DEPARTMENT_NAME AS 학과명, CAPACITY AS 정원
FROM  TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30; 

--B6번
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

--B7번
SELECT STUDENT_NAME AS 학생명 
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

--B8번
SELECT CLASS_NO FROM TB_GRADE WHERE CLASS_NO IS NOT NULL;

--B9번
SELECT DISTINCT CATEGORY AS 계열
FROM TB_DEPARTMENT;

--B10번
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE SUBSTR(ENTRANCE_DATE, 1, 2) = '02';

--F1번
SELECT STUDENT_NO AS 학번, STUDENT_NAME AS 이름, TO_CHAR(TO_DATE(ENTRANCE_DATE, 'RR/MM/DD'), 'YYYY-MM-DD') AS 입학년도
FROM TB_STUDENT;

SELECT TO_CHAR(TO_DATE(ENTRANCE_DATE, 'RR/MM/DD'), 'YYYY-MM-DD') AS 입학년도
FROM TB_STUDENT;

--F2번
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE NOT LENGTH(PROFESSOR_NAME) = 3;

--F3번
SELECT PROFESSOR_NAME, EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(PROFESSOR_SSN, 1, 6),'RRMMDD')) AS 연령
FROM TB_PROFESSOR;

SELECT 
  PROFESSOR_NAME,
  FLOOR(MONTHS_BETWEEN(SYSDATE, TO_DATE(SUBSTR(PROFESSOR_SSN, 1, 6), 'RRMMDD')) / 12) AS 연령
FROM TB_PROFESSOR;


SELECT EXTRACT(YEAR FROM SYSDATE) FROM DUAL;
SELECT TO_DATE(SUBSTR(PROFESSOR_SSN, 1,2), 'RR/MM/DD') FROM TB_PROFESSOR;
SELECT EXTRACT(YEAR FROM TO_DATE(SUBSTR(PROFESSOR_SSN, 1, 6),'RRMMDD')) FROM TB_PROFESSOR;

--F4번
SELECT SUBSTR(PROFESSOR_NAME, 2) AS 이름
FROM TB_PROFESSOR;

--F5번
SELECT STUDENT_NO, EXTRACT(YEAR FROM ENTRANCE_DATE) -  EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN, 1, 6),'RRMMDD')) AS 나이
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) -  EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN, 1, 6),'RRMMDD')) = 19;

--F6번
SELECT * FROM TB_STUDENT WHERE STUDENT_NO = 'A031341';

SELECT TO_CHAR(TO_DATE('20/12/25', 'RR/MM/DD'), 'D') FROM DUAL;
SELECT TO_CHAR(TO_DATE('2020/12/25', 'YYYY/MM/DD'), 'DY', 'NLS_DATE_LANGUAGE=KOREAN') AS 요일
FROM DUAL;

--F7번
SELECT TO_DATE('99/10/11','RR/MM/DD') FROM DUAL;

--F8번
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM TO_DATE(SUBSTR(ENTRANCE_DATE,1,8),'RR/MM/DD')) > 2000;

--F9번
SELECT ROUND(AVG(POINT),1) AS 평점 
FROM TB_GRADE 
WHERE STUDENT_NO = 'A517178';

--F10번
SELECT DEPARTMENT_NO AS 학과번호, CAPACITY AS "학생수(명)"
FROM TB_DEPARTMENT;

--F11번
SELECT COUNT(*) AS 학생수
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

--F12번
SELECT  SUBSTR(TERM_NO, 1, 4) AS 년도, AVG(POINT) AS "년도 별 평균점수"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO, 1, 4);

--F13번
SELECT DEPARTMENT_NO AS 학과, COUNT(*) AS 휴학생수
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO ASC;

--F14번
SELECT STUDENT_NAME AS 동일이름, COUNT(*) AS 동명인수
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(*) != 1;

--F15번
SELECT  SUBSTR(TERM_NO, 1, 4) AS 년도,SUBSTR(TERM_NO, 5, 2) AS "학기" ,AVG(POINT) AS "년도 별 평균점수"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY TERM_NO;

SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_CLASS;
SELECT * FROM TB_PROFESSOR WHERE PROFESSOR_NAME = '서미화';
SELECT * FROM TB_STUDENT;
SELECT * FROM TB_GRADE;

--O1번
SELECT STUDENT_NAME AS "학생 이름", STUDENT_ADDRESS AS "주소지"
FROM TB_STUDENT
ORDER BY STUDENT_NAME ASC;

--02번
SELECT STUDENT_NAME AS 학생이름, STUDENT_SSN AS 주민번호
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY STUDENT_SSN DESC;

--O3번
SELECT STUDENT_NAME AS 학생이름, STUDENT_NO AS 학번, STUDENT_ADDRESS AS "거주지 주소" 
FROM TB_STUDENT 
--WHERE STUDENT_ADDRESS LIKE '경기도%' OR '강원도%';
WHERE STUDENT_ADDRESS LIKE '강원도%' OR STUDENT_ADDRESS LIKE '경기도%';

--04번
SELECT *
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO FROM TB_DEPARTMENT WHERE DEPARTMENT_NAME = '법학과')
ORDER BY PROFESSOR_SSN;

--05번
SELECT STUDENT_NO, POINT
FROM TB_GRADE
WHERE CLASS_NO = 'C3118100'
ORDER BY POINT DESC, STUDENT_NO ASC;

--06번
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
ORDER BY STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME;

--07번
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO);

--08번
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS 
JOIN TB_PROFESSOR USING(DEPARTMENT_NO);

--9번
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS 
JOIN TB_PROFESSOR USING(DEPARTMENT_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE CATEGORY = '인문사회';

--10번
SELECT STUDENT_NO, STUDENT_NAME, ROUND(AVG(POINT),1) AS 전체평점
FROM TB_GRADE
JOIN TB_STUDENT USING(STUDENT_NO)
GROUP BY STUDENT_NO, STUDENT_NAME;


