--F1번)
SELECT STUDENT_NO AS 학번, STUDENT_NAME AS 이름, TO_CHAR(TO_DATE(ENTRANCE_DATE, 'RR/MM/DD'), 'YYYY-MM-DD') AS 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002';

--답안)
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD') 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002';

--F2번
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE NOT LENGTH(PROFESSOR_NAME) = 3;

--답안)
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 3;

--F3번
SELECT PROFESSOR_NAME, EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(PROFESSOR_SSN, 1, 6),'RRMMDD')) AS 나이
FROM TB_PROFESSOR
ORDER BY 나이;
--F3-2)
SELECT PROFESSOR_NAME, FLOOR(MONTHS_BETWEEN(SYSDATE, TO_DATE(SUBSTR(PROFESSOR_SSN, 1, 6),'RRMMDD'))/12) AS 나이
FROM TB_PROFESSOR
ORDER BY 나이 ASC;
//RRMMDD를 사용하면 491130인 경우 -> 2049로 인식(1949가 아닌) 따라서 -25가 나올 수 도

--답안)
SELECT PROFESSOR_NAME 교수이름, EXTRACT(YEAR FROM SYSDATE) - (19 || SUBSTR(PROFESSOR_SSN, 1, 2)) 나이
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = 1
ORDER BY 나이;


SELECT EXTRACT(YEAR FROM SYSDATE) FROM DUAL;
SELECT TO_DATE(SUBSTR(PROFESSOR_SSN, 1,2), 'RR/MM/DD') FROM TB_PROFESSOR;
SELECT EXTRACT(YEAR FROM TO_DATE(SUBSTR(PROFESSOR_SSN, 1, 6),'RRMMDD')) FROM TB_PROFESSOR;

--F4번
SELECT SUBSTR(PROFESSOR_NAME, 2) AS 이름
FROM TB_PROFESSOR;

--답안)
SELECT SUBSTR(PROFESSOR_NAME, 2) 이름
FROM TB_PROFESSOR;

--F5번
SELECT STUDENT_NO, EXTRACT(YEAR FROM ENTRANCE_DATE) -  EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN, 1, 6),'RRMMDD')) AS 나이
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) -  EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN, 1, 6),'RRMMDD')) != 19;

SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN, 1, 6))) > 19;

--F6번
SELECT * FROM TB_STUDENT WHERE STUDENT_NO = 'A031341';

SELECT TO_CHAR(TO_DATE('20/12/25', 'RR/MM/DD'), 'D') FROM DUAL;
SELECT TO_CHAR(TO_DATE('2020/12/25', 'YYYY/MM/DD'), 'DY', 'NLS_DATE_LANGUAGE=KOREAN') AS 요일
FROM DUAL;

--F7번
SELECT TO_DATE('99/10/11','RR/MM/DD') FROM DUAL;

--F8번
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM TO_DATE(SUBSTR(ENTRANCE_DATE,1,8),'RR/MM/DD')) > 2000;

--F9번
SELECT ROUND(AVG(POINT),1) AS 평점 
FROM TB_GRADE 
WHERE STUDENT_NO = 'A517178';

--F10번
SELECT DEPARTMENT_NO AS 학과번호, CAPACITY AS "학생수(명)"
FROM TB_DEPARTMENT;

--F11번
SELECT COUNT(*) AS 학생수
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

--F12번
SELECT  SUBSTR(TERM_NO, 1, 4) AS 년도, AVG(POINT) AS "년도 별 평균점수"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO, 1, 4);

--F13번
SELECT DEPARTMENT_NO AS 학과, COUNT(*) AS 휴학생수
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO ASC;

--F14번
SELECT STUDENT_NAME AS 동일이름, COUNT(*) AS 동명인수
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(*) != 1;

--F15번
SELECT  SUBSTR(TERM_NO, 1, 4) AS 년도,SUBSTR(TERM_NO, 5, 2) AS "학기" ,AVG(POINT) AS "년도 별 평균점수"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY TERM_NO;
